In [5]:
import tensorflow as tf

# Step 1: Create a random tensor of shape (4, 6)
tensor = tf.random.uniform(shape=(4, 6), minval=1, maxval=10, dtype=tf.int32)
print("Original Tensor:\n", tensor.numpy())

# Step 2: Find its rank and shape
rank = tf.rank(tensor)
shape = tf.shape(tensor)
print("Rank of the tensor:", rank.numpy())
print("Shape of the tensor:", shape.numpy())

# Step 3: Reshape it into (2, 3, 4) and transpose it to (3, 2, 4)
reshaped_tensor = tf.reshape(tensor, (2, 3, 4))
print("Reshaped Tensor (2, 3, 4):\n", reshaped_tensor.numpy())

transposed_tensor = tf.transpose(reshaped_tensor, perm=[1, 0, 2])
print("Transposed Tensor (3, 2, 4):\n", transposed_tensor.numpy())

# Step 4: Broadcast a smaller tensor (1, 4) to match the larger tensor and add them
small_tensor = tf.constant([[1, 2, 3, 4]])  # Shape (1, 4)
broadcasted_tensor = tf.broadcast_to(small_tensor, transposed_tensor.shape)
print("Broadcasted Tensor:\n", broadcasted_tensor.numpy())

result = transposed_tensor + broadcasted_tensor
print("Result after Broadcasting and Addition:\n", result.numpy())

#5 Question: Explanation of Broadcasting
print("\nExplanation of Broadcasting:")
print("Broadcasting is a way to make tensors of different shapes work together in operations like addition, subtraction, and other "
      "TensorFlow automatically stretches the smaller tensor to match the shape of the larger tensor. "
      "For example, a tensor of shape (1, 4) is repeated to match the shape (3, 2, 4) so that element-wise addition can be performed.")

Original Tensor:
 [[8 9 4 1 4 5]
 [7 1 7 8 1 7]
 [5 7 4 7 5 1]
 [7 7 1 5 7 6]]
Rank of the tensor: 2
Shape of the tensor: [4 6]
Reshaped Tensor (2, 3, 4):
 [[[8 9 4 1]
  [4 5 7 1]
  [7 8 1 7]]

 [[5 7 4 7]
  [5 1 7 7]
  [1 5 7 6]]]
Transposed Tensor (3, 2, 4):
 [[[8 9 4 1]
  [5 7 4 7]]

 [[4 5 7 1]
  [5 1 7 7]]

 [[7 8 1 7]
  [1 5 7 6]]]
Broadcasted Tensor:
 [[[1 2 3 4]
  [1 2 3 4]]

 [[1 2 3 4]
  [1 2 3 4]]

 [[1 2 3 4]
  [1 2 3 4]]]
Result after Broadcasting and Addition:
 [[[ 9 11  7  5]
  [ 6  9  7 11]]

 [[ 5  7 10  5]
  [ 6  3 10 11]]

 [[ 8 10  4 11]
  [ 2  7 10 10]]]

Explanation of Broadcasting:
Broadcasting is a way to make tensors of different shapes work together in operations like addition, subtraction, and other TensorFlow automatically stretches the smaller tensor to match the shape of the larger tensor. For example, a tensor of shape (1, 4) is repeated to match the shape (3, 2, 4) so that element-wise addition can be performed.
